---
name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    # Restrict permissions of the GITHUB_TOKEN.
    # Docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      actions: read
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        uses: starkware-libs/merge-gatekeeper@90b067dac75b94c354c3f47a0462d126eae40413 # v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
