---
name: automerge-gate

on:
  pull_request:
    types: [opened, synchronize, reopened, auto_merge_enabled]
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gate:
    name: automerge-gate/all-passed
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Restrict permissions of the GITHUB_TOKEN.
    # Docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      checks: read
      pull-requests: read
      actions: read
    steps:
      - name: Run automerge-gate
        uses: pkgdeps/automerge-gate@v4.0.0
        with:
          gate-mode: public
