---
name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    # Restrict permissions of the GITHUB_TOKEN.
    # Docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      actions: read
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        uses: starkware-libs/merge-gatekeeper@9ea5ad731de74662f5f42e9f8b3a72fe6e2159dc # v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
